### PR TITLE
new logic for search

### PR DESCRIPTION
**Pull request by pu6elozed**
now search from selection to top,
search closest parent class

### CODE REVIEW

**Comment by bancek** [comment]
Please use camel case for variable and function names and write some tests. Tests should indicate new functionality and prevent regressions (old behavior should still work).

**Comment by pu6elozed** [comment]
Check this commit please.

**Comment by pu6elozed** [comment]
Please check this commits @bancek

**Comment by bancek** [comment]
This has been merged manually. New version has been released.

**Pull request merged**
